/**
 * FincTools v2 — Tools Data
 * Data & konfigurasi untuk 46 tools
 */

import type { ToolData, KategoriTool, KategoriToolConfig } from './types'

// ─── Kategori Config ──────────────────────────────

export const kategoriToolConfig: Record<KategoriTool, KategoriToolConfig> = {
  trading: {
    nama: 'Trading',
    deskripsi: 'Tools manajemen risiko, position sizing, dan analisa performa trading',
    warna: 'blue',
    iconBg: 'bg-blue-500',
    badge: 'text-blue-700 dark:text-blue-300 bg-blue-50 dark:bg-blue-950/30',
  },
  pajak: {
    nama: 'Pajak',
    deskripsi: 'Tools perhitungan PPh 21, pajak investasi, UMKM, PPN, dan zakat',
    warna: 'purple',
    iconBg: 'bg-purple-500',
    badge: 'text-purple-700 dark:text-purple-300 bg-purple-50 dark:bg-purple-950/30',
  },
  investasi: {
    nama: 'Investasi',
    deskripsi: 'Tools simulasi DCA, reksa dana, SBN, obligasi, emas, dan dividen',
    warna: 'emerald',
    iconBg: 'bg-emerald-500',
    badge: 'text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/30',
  },
  'personal-finance': {
    nama: 'Personal Finance',
    deskripsi: 'Tools perencanaan FIRE, dana darurat, budgeting, utang, dan net worth',
    warna: 'sky',
    iconBg: 'bg-sky-500',
    badge: 'text-sky-700 dark:text-sky-300 bg-sky-50 dark:bg-sky-950/30',
  },
  'kredit-properti': {
    nama: 'Kredit & Properti',
    deskripsi: 'Tools analisa KPR, refinancing, buy vs rent, dan investasi properti',
    warna: 'orange',
    iconBg: 'bg-orange-500',
    badge: 'text-orange-700 dark:text-orange-300 bg-orange-50 dark:bg-orange-950/30',
  },
  saham: {
    nama: 'Saham',
    deskripsi: 'Tools strategi averaging, optimasi entry, dan kalkulasi break-even saham',
    warna: 'indigo',
    iconBg: 'bg-indigo-500',
    badge: 'text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-950/30',
  },
  kripto: {
    nama: 'Kripto',
    deskripsi: 'Tools DCA kripto, staking, manajemen risiko, likuidasi, dan funding rate',
    warna: 'amber',
    iconBg: 'bg-amber-500',
    badge: 'text-amber-700 dark:text-amber-300 bg-amber-50 dark:bg-amber-950/30',
  },
}

// ─── Tools Database ───────────────────────────────

export const toolsDatabase: ToolData[] = [

  // ══════════════════════════════════════════════
  // TRADING
  // ══════════════════════════════════════════════
  {
    slug: 'risk-manager',
    kategori: 'trading',
    nama: 'Risk Manager',
    deskripsi: 'Hitung ukuran posisi trading optimal berdasarkan modal dan persentase risiko per trade.',
    keywords: ['risk manager', 'position sizing', 'manajemen risiko trading', 'lot size calculator'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Modal', desc: 'Masukkan total modal trading kamu dalam Rupiah.' },
      { judul: 'Tentukan % Risiko', desc: 'Risiko per trade yang disarankan: 1-2% untuk konservatif, maksimal 5% untuk agresif.' },
      { judul: 'Isi Stop Loss', desc: 'Masukkan jarak stop loss dalam pips dari harga entry.' },
      { judul: 'Masukkan Pip Value', desc: 'Nilai per pip untuk instrumen yang diperdagangkan.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan ukuran lot optimal dan analisa profil risiko kamu.' },
    ],
    faqs: [
      { q: 'Berapa persen risiko yang ideal per trade?', a: 'Standar trader profesional adalah 1-2% per trade. Dengan risiko 1%, kamu butuh 100 kali loss berturut-turut untuk kehilangan semua modal — skenario yang hampir mustahil.' },
      { q: 'Apa itu pip value?', a: 'Pip value adalah nilai moneter dari satu pergerakan pip. Untuk EUR/USD dengan lot 1 standar, 1 pip = $10. Untuk pair yang melibatkan IDR, nilainya berbeda.' },
      { q: 'Apakah tool ini cocok untuk saham?', a: 'Tool ini dirancang untuk forex dan CFD. Untuk saham Indonesia, gunakan Entry Price Optimizer yang memperhitungkan satuan lot saham IDX.' },
    ],
    references: ['Van K. Tharp — Trade Your Way to Financial Freedom (1998)', 'Bank for International Settlements — FX and OTC derivatives statistics'],
    relatedTools: ['trading/trade-analyzer', 'trading/stop-loss-optimizer', 'trading/max-loss-guardian'],
  },
  {
    slug: 'trade-analyzer',
    kategori: 'trading',
    nama: 'Trade Analyzer',
    deskripsi: 'Analisa kelayakan trade berdasarkan risk/reward ratio, potensi profit, dan potensi loss.',
    keywords: ['trade analyzer', 'risk reward ratio', 'analisa trade', 'potensi profit trading'],
    tipe: 'K+A',
    tombol: 'Analisa Trade',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Entry', desc: 'Harga di mana kamu berencana masuk posisi.' },
      { judul: 'Masukkan Stop Loss', desc: 'Level harga di mana posisi akan ditutup jika rugi.' },
      { judul: 'Masukkan Take Profit', desc: 'Level harga target keuntungan.' },
      { judul: 'Isi Lot dan Pip Value', desc: 'Ukuran posisi dan nilai pip instrumen yang diperdagangkan.' },
      { judul: 'Klik Analisa Trade', desc: 'Dapatkan R/R ratio, potensi profit/loss, dan rekomendasi.' },
    ],
    faqs: [
      { q: 'Berapa R/R ratio minimum yang layak?', a: 'Minimal 1:2 — artinya untuk setiap Rp 1 yang dirisikoan, potensi keuntungannya Rp 2. Dengan R/R 1:2, kamu bisa profitable meski hanya 40% trade yang menang.' },
      { q: 'Apakah R/R yang tinggi selalu lebih baik?', a: 'Tidak selalu. R/R sangat tinggi (misal 1:10) sering kali berarti take profit terlalu jauh dan probabilitas kena sangat rendah. Keseimbangan antara R/R dan win rate adalah kunci.' },
    ],
    references: ['Mark Douglas — Trading in the Zone (2000)', 'Alexander Elder — Come into My Trading Room (2002)'],
    relatedTools: ['trading/risk-manager', 'trading/win-rate-expectancy-tracker', 'trading/kelly-criterion-optimizer'],
  },
  {
    slug: 'stop-loss-optimizer',
    kategori: 'trading',
    nama: 'Stop Loss Optimizer',
    deskripsi: 'Optimalkan penempatan stop loss menggunakan ATR (Average True Range) untuk setiap instrumen.',
    keywords: ['stop loss optimizer', 'ATR stop loss', 'average true range', 'posisi stop loss trading'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Entry', desc: 'Harga entry posisi yang direncanakan.' },
      { judul: 'Masukkan Nilai ATR', desc: 'ATR bisa dilihat di platform trading kamu (biasanya periode 14).' },
      { judul: 'Pilih Multiplier ATR', desc: 'Standar: 1.5x–2x ATR untuk stop loss yang tidak mudah kena noise pasar.' },
      { judul: 'Tentukan Modal & Risiko', desc: 'Masukkan modal dan persentase risiko untuk kalkulasi ukuran lot.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan level stop loss, ukuran lot, dan analisa.' },
    ],
    faqs: [
      { q: 'Mengapa stop loss berbasis ATR lebih baik dari persentase tetap?', a: 'ATR mencerminkan volatilitas aktual instrumen. Stop loss berbasis ATR menyesuaikan dengan kondisi pasar — lebih lebar saat volatil, lebih sempit saat tenang. Ini mengurangi kemungkinan stop loss kena karena noise biasa.' },
      { q: 'Berapa multiplier ATR yang direkomendasikan?', a: '1.5x–2x ATR adalah standar umum. Untuk day trading gunakan lebih ketat (1x), untuk swing trading bisa lebih longgar (2x–3x).' },
    ],
    references: ['J. Welles Wilder Jr. — New Concepts in Technical Trading Systems (1978)', 'John J. Murphy — Technical Analysis of the Financial Markets (1999)'],
    relatedTools: ['trading/risk-manager', 'trading/trade-analyzer', 'trading/margin-leverage-guard'],
  },
  {
    slug: 'max-loss-guardian',
    kategori: 'trading',
    nama: 'Max Loss Guardian',
    deskripsi: 'Tentukan batas maksimum kerugian harian dan mingguan untuk menjaga modal dari drawdown parah.',
    keywords: ['max loss guardian', 'batas loss trading', 'drawdown protection', 'circuit breaker trading'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Modal', desc: 'Total modal trading aktif.' },
      { judul: 'Tentukan Max Loss Harian', desc: 'Persentase maksimum yang boleh hilang dalam satu hari — rekomendasi 3–5%.' },
      { judul: 'Tentukan Max Loss Mingguan', desc: 'Batas kerugian per minggu — rekomendasi 8–10%.' },
      { judul: 'Masukkan Risiko per Trade', desc: 'Persentase risiko per trade yang biasa kamu gunakan.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan batas loss nominal dan maksimum trade per hari/minggu.' },
    ],
    faqs: [
      { q: 'Mengapa perlu batas loss harian?', a: 'Setelah beberapa loss berturut-turut, emosi mempengaruhi keputusan. Trader yang sudah "revenge trading" sering membuat keputusan terburuk. Batas loss harian memaksa kamu berhenti sebelum kondisi semakin parah.' },
      { q: 'Apa yang harus dilakukan setelah mencapai batas loss?', a: 'Berhenti trading untuk hari itu. Tidak ada pengecualian. Gunakan waktu untuk menganalisa apa yang salah, bukan untuk memaksakan recovery.' },
    ],
    references: ['Brett Steenbarger — The Psychology of Trading (2002)', 'Mark Douglas — The Disciplined Trader (1990)'],
    relatedTools: ['trading/risk-manager', 'trading/drawdown-recovery-planner', 'trading/trading-performance-analyzer'],
  },
  {
    slug: 'trading-performance-analyzer',
    kategori: 'trading',
    nama: 'Trading Performance Analyzer',
    deskripsi: 'Analisa performa trading secara komprehensif: win rate, profit factor, expectancy, dan total profit.',
    keywords: ['trading performance', 'profit factor', 'win rate', 'analisa performa trading', 'trading statistics'],
    tipe: 'A+G',
    tombol: 'Analisa Performa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Total Trade', desc: 'Jumlah total trade yang dianalisa.' },
      { judul: 'Masukkan Jumlah Win', desc: 'Berapa trade yang menghasilkan profit.' },
      { judul: 'Masukkan Average Win', desc: 'Rata-rata keuntungan per trade yang menang (Rp).' },
      { judul: 'Masukkan Average Loss', desc: 'Rata-rata kerugian per trade yang kalah (Rp).' },
      { judul: 'Klik Analisa Performa', desc: 'Dapatkan statistik lengkap dan visualisasi performa.' },
    ],
    faqs: [
      { q: 'Apa itu profit factor?', a: 'Profit factor adalah rasio total gross profit dibagi total gross loss. PF > 1 berarti profitable. PF ≥ 1.5 dianggap strategi yang solid. PF < 1 berarti strategi sedang merugi.' },
      { q: 'Berapa win rate minimum agar strategi bisa profitable?', a: 'Bergantung pada R/R ratio. Dengan R/R 1:1, butuh win rate > 50%. Dengan R/R 1:2, cukup win rate 34%. Dengan R/R 1:3, cukup 25% win rate.' },
    ],
    references: ['Ralph Vince — The Mathematics of Money Management (1992)', 'Tushar Chande — Beyond Technical Analysis (2001)'],
    relatedTools: ['trading/win-rate-expectancy-tracker', 'trading/drawdown-recovery-planner', 'trading/streak-analyzer'],
  },
  {
    slug: 'win-rate-expectancy-tracker',
    kategori: 'trading',
    nama: 'Win Rate & Expectancy Tracker',
    deskripsi: 'Hitung expectancy per trade dan proyeksi keuntungan bulanan berdasarkan win rate dan R/R ratio.',
    keywords: ['win rate trading', 'expectancy', 'proyeksi profit trading', 'break even win rate'],
    tipe: 'K+A+G',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Win Rate', desc: 'Persentase trade yang menghasilkan profit dari histori trading kamu.' },
      { judul: 'Masukkan Average Win', desc: 'Rata-rata keuntungan per trade menang dalam Rupiah.' },
      { judul: 'Masukkan Average Loss', desc: 'Rata-rata kerugian per trade kalah dalam Rupiah.' },
      { judul: 'Masukkan Trade per Bulan', desc: 'Estimasi jumlah trade yang biasa kamu lakukan per bulan.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan expectancy, break-even win rate, dan proyeksi bulanan.' },
    ],
    faqs: [
      { q: 'Apa itu expectancy dan mengapa penting?', a: 'Expectancy adalah rata-rata keuntungan atau kerugian per trade yang diharapkan. Expectancy positif berarti strategi menghasilkan profit jangka panjang meski tidak setiap trade menang. Ini metrik terpenting dalam trading.' },
      { q: 'Apa itu break-even win rate?', a: 'Win rate minimum yang dibutuhkan agar strategi tidak rugi. Dihitung dari: Loss / (Win + Loss). Jika win rate kamu di bawah ini, strategi sedang merugi secara ekspektasi.' },
    ],
    references: ['Van K. Tharp — Trade Your Way to Financial Freedom (1998)'],
    relatedTools: ['trading/trading-performance-analyzer', 'trading/kelly-criterion-optimizer', 'trading/streak-analyzer'],
  },
  {
    slug: 'drawdown-recovery-planner',
    kategori: 'trading',
    nama: 'Drawdown Recovery Planner',
    deskripsi: 'Simulasikan berapa lama waktu dan berapa trade yang dibutuhkan untuk recovery dari drawdown.',
    keywords: ['drawdown recovery', 'pemulihan drawdown trading', 'berapa lama recovery trading'],
    tipe: 'S+G',
    tombol: 'Simulasikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Modal Awal', desc: 'Modal sebelum drawdown terjadi.' },
      { judul: 'Masukkan Modal Sekarang', desc: 'Modal yang tersisa setelah drawdown.' },
      { judul: 'Masukkan Win Rate', desc: 'Win rate strategi trading kamu saat ini.' },
      { judul: 'Masukkan R/R Ratio', desc: 'Risk/reward ratio rata-rata per trade.' },
      { judul: 'Masukkan Risiko per Trade', desc: 'Persentase modal yang dirisikoan per trade.' },
      { judul: 'Klik Simulasikan', desc: 'Lihat estimasi jumlah trade dan waktu untuk recovery.' },
    ],
    faqs: [
      { q: 'Kenapa recovery dari drawdown 50% membutuhkan gain 100%?', a: 'Matematika asimetris. Jika modal turun 50% dari Rp 10 juta menjadi Rp 5 juta, kamu butuh gain 100% dari Rp 5 juta untuk kembali ke Rp 10 juta. Inilah mengapa mencegah drawdown besar jauh lebih penting dari mengejar profit.' },
    ],
    references: ['Fred Gehm — Quantitative Trading and Money Management (1995)'],
    relatedTools: ['trading/max-loss-guardian', 'trading/trading-performance-analyzer', 'trading/probability-of-ruin-analyzer'],
  },
  {
    slug: 'pip-profit-analyzer',
    kategori: 'trading',
    nama: 'Pip & Profit Analyzer',
    deskripsi: 'Hitung nilai pip dan total profit atau loss dari posisi trading forex berdasarkan ukuran lot.',
    keywords: ['pip value', 'kalkulasi profit forex', 'pip calculator', 'nilai pip forex'],
    tipe: 'K',
    tombol: 'Hitung',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Ukuran Lot', desc: 'Ukuran lot posisi trading kamu.' },
      { judul: 'Masukkan Jumlah Pip', desc: 'Pergerakan harga dalam pips.' },
      { judul: 'Masukkan Pip Value', desc: 'Nilai per pip untuk instrumen yang diperdagangkan.' },
      { judul: 'Pilih Profit atau Loss', desc: 'Tentukan apakah pergerakan ini menguntungkan atau merugikan.' },
      { judul: 'Klik Hitung', desc: 'Dapatkan nilai pip dan total P&L.' },
    ],
    faqs: [
      { q: 'Bagaimana cara mengetahui pip value suatu instrumen?', a: 'Pip value bergantung pada pair dan ukuran lot. Untuk standard lot EUR/USD, 1 pip = $10 atau sekitar Rp 155.000. Platform trading biasanya menampilkan pip value secara otomatis.' },
    ],
    references: ['BIS Triennial Central Bank Survey (2022)'],
    relatedTools: ['trading/risk-manager', 'trading/trade-analyzer', 'trading/swap-cost-estimator'],
  },
  {
    slug: 'margin-leverage-guard',
    kategori: 'trading',
    nama: 'Margin & Leverage Guard',
    deskripsi: 'Pantau level margin dan leverage untuk mencegah margin call dan kehilangan modal secara tiba-tiba.',
    keywords: ['margin call', 'leverage trading', 'margin level', 'free margin trading'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Modal', desc: 'Ekuitas akun trading kamu saat ini.' },
      { judul: 'Tentukan Leverage', desc: 'Leverage yang diberikan broker (misal 1:100, 1:200).' },
      { judul: 'Masukkan Ukuran Lot', desc: 'Total lot posisi yang sedang atau akan dibuka.' },
      { judul: 'Masukkan Harga & Contract Size', desc: 'Harga instrumen dan ukuran kontrak standar.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan margin level, free margin, dan analisa risiko.' },
    ],
    faqs: [
      { q: 'Apa itu margin call?', a: 'Margin call terjadi saat margin level turun di bawah threshold broker (biasanya 100%). Broker akan meminta tambahan dana atau menutup posisi secara paksa. Ini bisa terjadi sangat cepat saat pasar bergerak tajam.' },
      { q: 'Leverage berapa yang aman?', a: 'Semakin rendah leverage efektif semakin aman. Trader profesional jarang menggunakan lebih dari 10:1 leverage efektif meski broker menawarkan hingga 500:1. Leverage tinggi memperbesar profit dan loss secara sama.' },
    ],
    references: ['ESMA — Retail Investor Losses from CFDs (2019)'],
    relatedTools: ['trading/risk-manager', 'trading/stop-loss-optimizer', 'trading/max-loss-guardian'],
  },
  {
    slug: 'swap-cost-estimator',
    kategori: 'trading',
    nama: 'Swap Cost Estimator',
    deskripsi: 'Estimasi biaya swap (rollover) untuk posisi yang ditahan lebih dari satu malam.',
    keywords: ['swap cost', 'rollover fee forex', 'biaya overnight forex', 'swap rate calculator'],
    tipe: 'K',
    tombol: 'Hitung',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Ukuran Lot', desc: 'Ukuran posisi yang ditahan.' },
      { judul: 'Masukkan Swap Rate', desc: 'Swap rate dalam pips per malam (lihat di platform trading atau website broker).' },
      { judul: 'Masukkan Jumlah Malam', desc: 'Berapa malam posisi akan ditahan.' },
      { judul: 'Masukkan Pip Value', desc: 'Nilai per pip instrumen yang diperdagangkan.' },
      { judul: 'Klik Hitung', desc: 'Dapatkan total biaya swap yang perlu diperhitungkan.' },
    ],
    faqs: [
      { q: 'Kapan swap dikenakan?', a: 'Swap dikenakan setiap hari pada pukul 00:00 server time broker (biasanya GMT+2 atau GMT+3). Pada hari Rabu ke Kamis, swap dikalikan 3 untuk menutup weekend.' },
      { q: 'Apakah swap bisa positif?', a: 'Ya. Jika kamu memegang posisi buy pada pair dengan interest rate tinggi, swap bisa positif (kamu menerima pembayaran). Ini disebut carry trade strategy.' },
    ],
    references: ['Bank for International Settlements — FX global code (2021)'],
    relatedTools: ['trading/pip-profit-analyzer', 'trading/margin-leverage-guard', 'trading/risk-manager'],
  },
  {
    slug: 'kelly-criterion-optimizer',
    kategori: 'trading',
    nama: 'Kelly Criterion Optimizer',
    deskripsi: 'Hitung persentase modal optimal per trade menggunakan formula Kelly Criterion.',
    keywords: ['kelly criterion', 'optimal position sizing', 'kelly formula trading', 'money management formula'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Win Rate', desc: 'Persentase trade yang menang dari histori kamu.' },
      { judul: 'Masukkan R/R Ratio', desc: 'Rata-rata reward dibagi rata-rata risk per trade.' },
      { judul: 'Masukkan Modal', desc: 'Total modal trading aktif.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan % Kelly, Half Kelly yang direkomendasikan, dan analisa.' },
    ],
    faqs: [
      { q: 'Mengapa menggunakan Half Kelly bukan Full Kelly?', a: 'Full Kelly memaksimalkan pertumbuhan modal secara matematis tapi menghasilkan drawdown yang sangat parah. Half Kelly memberikan 75% pertumbuhan full Kelly dengan hanya 25% dari drawdownnya — trade-off yang jauh lebih baik.' },
      { q: 'Apakah Kelly Criterion selalu tepat?', a: 'Kelly Criterion optimal hanya jika win rate dan R/R ratio akurat. Dalam praktiknya, gunakan sebagai panduan batas atas, bukan angka pasti. Selalu konservatif dalam implementasinya.' },
    ],
    references: ['J.L. Kelly Jr. — A New Interpretation of Information Rate (Bell System Technical Journal, 1956)', 'Ed Thorp — Beat the Dealer (1962)'],
    relatedTools: ['trading/risk-manager', 'trading/win-rate-expectancy-tracker', 'trading/probability-of-ruin-analyzer'],
  },
  {
    slug: 'probability-of-ruin-analyzer',
    kategori: 'trading',
    nama: 'Probability of Ruin Analyzer',
    deskripsi: 'Hitung probabilitas kehilangan modal hingga batas tertentu berdasarkan win rate dan manajemen risiko.',
    keywords: ['probability of ruin', 'probabilitas ruin trading', 'risiko kebangkrutan trading', 'ruin analysis'],
    tipe: 'A',
    tombol: 'Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Win Rate', desc: 'Persentase trade yang menang.' },
      { judul: 'Masukkan R/R Ratio', desc: 'Rata-rata reward per unit risk.' },
      { judul: 'Masukkan Risiko per Trade', desc: 'Persentase modal yang dirisikoan per trade.' },
      { judul: 'Tentukan Target Ruin', desc: 'Berapa persen loss yang dianggap "ruin" (misal 50%).' },
      { judul: 'Klik Analisa', desc: 'Dapatkan probabilitas ruin dan skor keamanan.' },
    ],
    faqs: [
      { q: 'Probabilitas ruin berapa yang masih aman?', a: 'Di bawah 5% dianggap sangat aman. Antara 5–25% masih bisa diterima tapi perlu perbaikan. Di atas 25% menunjukkan strategi atau money management yang perlu dirombak.' },
    ],
    references: ['N.J. Balsara — Money Management Strategies for Futures Traders (1992)'],
    relatedTools: ['trading/kelly-criterion-optimizer', 'trading/drawdown-recovery-planner', 'trading/max-loss-guardian'],
  },
  {
    slug: 'streak-analyzer',
    kategori: 'trading',
    nama: 'Streak Analyzer',
    deskripsi: 'Analisa probabilitas win streak dan loss streak berdasarkan win rate untuk persiapan mental trading.',
    keywords: ['streak analyzer', 'loss streak trading', 'win streak probability', 'trading psychology statistics'],
    tipe: 'A',
    tombol: 'Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Win Rate', desc: 'Persentase trade yang menang.' },
      { judul: 'Tentukan Panjang Streak', desc: 'Berapa panjang streak yang ingin dianalisa probabilitasnya.' },
      { judul: 'Masukkan Total Trade', desc: 'Total trade dalam periode analisa.' },
      { judul: 'Klik Analisa', desc: 'Dapatkan probabilitas win/loss streak dan estimasi expected streak.' },
    ],
    faqs: [
      { q: 'Mengapa penting mengetahui probabilitas loss streak?', a: 'Loss streak 5-7 berturut-turut adalah hal normal secara statistik bahkan untuk strategi profitable. Tanpa mengetahui ini, trader sering panik dan mengubah strategi yang sebenarnya baik hanya karena periode loss normal.' },
    ],
    references: ['Brett Steenbarger — The Psychology of Trading (2002)'],
    relatedTools: ['trading/win-rate-expectancy-tracker', 'trading/trading-performance-analyzer', 'trading/probability-of-ruin-analyzer'],
  },

  // ══════════════════════════════════════════════
  // PAJAK
  // ══════════════════════════════════════════════
  {
    slug: 'tax-optimizer-pph21',
    kategori: 'pajak',
    nama: 'Tax Optimizer PPh 21',
    deskripsi: 'Hitung PPh 21 karyawan secara akurat berdasarkan UU HPP 2021 dan cek apakah potongan di slip gaji sudah benar.',
    keywords: ['PPh 21', 'pajak karyawan', 'hitung PPh 21', 'kalkulator pajak gaji', 'PTKP 2024'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Komponen Gaji', desc: 'Gaji pokok, tunjangan tetap, dan tunjangan tidak tetap per bulan.' },
      { judul: 'Pilih Status PTKP', desc: 'TK/0, K/0, K/1, K/2, atau K/3 sesuai status pernikahan dan tanggungan.' },
      { judul: 'Centang Status NPWP', desc: 'Tanpa NPWP dikenakan tarif 20% lebih tinggi.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan PPh 21 bulanan, take-home pay, dan analisa optimasi.' },
    ],
    faqs: [
      { q: 'Apa itu PTKP dan bagaimana mempengaruhi pajak?', a: 'PTKP (Penghasilan Tidak Kena Pajak) adalah batas penghasilan yang bebas pajak. Semakin tinggi PTKP (semakin banyak tanggungan), semakin kecil pajak yang harus dibayar.' },
      { q: 'Mengapa perlu NPWP?', a: 'Tanpa NPWP, tarif PPh 21 dikenakan 20% lebih tinggi. Membuat NPWP gratis di ereg.pajak.go.id dan bisa selesai dalam hari yang sama.' },
      { q: 'Kapan PPh 21 harus dibayar?', a: 'PPh 21 dipotong oleh pemberi kerja setiap bulan dan disetor paling lambat tanggal 10 bulan berikutnya. Karyawan tidak perlu menyetor sendiri.' },
    ],
    references: ['UU HPP No. 7 Tahun 2021', 'PMK No. 168/PMK.010/2023 tentang PTKP', 'Peraturan DJP PER-16/PJ/2016'],
    relatedTools: ['pajak/thr-tax-planner', 'pajak/freelancer-tax-estimator', 'pajak/investment-tax-report-generator'],
  },
  {
    slug: 'thr-tax-planner',
    kategori: 'pajak',
    nama: 'THR Tax Planner',
    deskripsi: 'Hitung pajak yang dikenakan atas THR dan berapa THR bersih yang akan kamu terima.',
    keywords: ['pajak THR', 'THR tax', 'hitung pajak tunjangan hari raya', 'THR bersih setelah pajak'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Gaji Bulanan', desc: 'Gaji pokok dan tunjangan tetap per bulan.' },
      { judul: 'Masukkan Jumlah THR', desc: 'Nominal THR yang akan diterima — biasanya 1 bulan gaji.' },
      { judul: 'Pilih Status PTKP', desc: 'Status pajak sesuai kondisi kamu.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan pajak THR, THR bersih, dan analisa.' },
    ],
    faqs: [
      { q: 'Bagaimana cara menghitung pajak THR?', a: 'THR ditambahkan ke penghasilan tahunan, lalu pajak dihitung ulang. Selisih antara pajak dengan THR dan tanpa THR adalah pajak atas THR tersebut. Ini disebut metode penggabungan penghasilan.' },
      { q: 'Apakah pajak THR bisa dikurangi?', a: 'Secara resmi tidak bisa dikurangi. Namun beberapa perusahaan menanggung pajak THR karyawan sebagai benefit — tanyakan ke HRD.' },
    ],
    references: ['UU HPP No. 7 Tahun 2021', 'SE DJP No. SE-14/PJ/2013 tentang pajak THR'],
    relatedTools: ['pajak/tax-optimizer-pph21', 'pajak/freelancer-tax-estimator'],
  },
  {
    slug: 'freelancer-tax-estimator',
    kategori: 'pajak',
    nama: 'Freelancer Tax Estimator',
    deskripsi: 'Estimasi pajak penghasilan untuk freelancer dan pekerja mandiri menggunakan norma penghitungan neto.',
    keywords: ['pajak freelancer', 'PPh freelancer', 'norma penghitungan neto', 'pajak pekerja mandiri'],
    tipe: 'K+A',
    tombol: 'Estimasi',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Penghasilan Bulanan', desc: 'Rata-rata penghasilan bruto per bulan dari pekerjaan freelance.' },
      { judul: 'Pilih Norma', desc: 'Persentase norma sesuai jenis pekerjaan — tersedia di Peraturan DJP.' },
      { judul: 'Pilih Status PTKP', desc: 'Status pernikahan dan tanggungan.' },
      { judul: 'Masukkan Bulan Kerja', desc: 'Berapa bulan kamu bekerja di tahun ini.' },
      { judul: 'Klik Estimasi', desc: 'Dapatkan estimasi PPh dan analisa optimasi.' },
    ],
    faqs: [
      { q: 'Apa itu norma penghitungan neto?', a: 'Norma adalah persentase yang digunakan untuk menghitung penghasilan neto dari bruto tanpa harus pembukuan. Berbeda per jenis pekerjaan, antara 20–75% dari penghasilan bruto.' },
      { q: 'Apakah freelancer wajib lapor SPT?', a: 'Ya. Semua WP dengan NPWP wajib lapor SPT tahunan meski tidak ada pajak yang terutang. Deadline: 31 Maret untuk WP Orang Pribadi.' },
    ],
    references: ['PER-17/PJ/2015 tentang Norma Penghitungan Penghasilan Neto', 'UU PPh No. 36 Tahun 2008'],
    relatedTools: ['pajak/tax-optimizer-pph21', 'pajak/umkm-tax-estimator'],
  },
  {
    slug: 'investment-tax-report-generator',
    kategori: 'pajak',
    nama: 'Investment Tax Report Generator',
    deskripsi: 'Hitung pajak dari berbagai instrumen investasi: saham, deposito, obligasi, dan dividen.',
    keywords: ['pajak investasi', 'pajak saham', 'pajak deposito', 'pajak dividen', 'laporan pajak investasi'],
    tipe: 'K',
    tombol: 'Buat Laporan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Nilai Jual Saham', desc: 'Total nilai transaksi jual saham dalam setahun (kena PPh final 0.1%).' },
      { judul: 'Masukkan Bunga Deposito', desc: 'Total bunga deposito yang diterima (kena PPh final 20%).' },
      { judul: 'Masukkan Bunga Obligasi', desc: 'Total bunga obligasi yang diterima (kena PPh final 10%).' },
      { judul: 'Masukkan Dividen', desc: 'Dividen lokal (10%) dan luar negeri (20%).' },
      { judul: 'Klik Buat Laporan', desc: 'Dapatkan rincian pajak per instrumen dan total kewajiban pajak.' },
    ],
    faqs: [
      { q: 'Apakah pajak saham dihitung dari profit atau nilai jual?', a: 'Dari nilai jual (gross), bukan profit. PPh final 0.1% dari total nilai transaksi jual, terlepas apakah transaksi untung atau rugi.' },
      { q: 'Apakah pajak investasi perlu dilaporkan di SPT?', a: 'PPh final tidak perlu dilaporkan sebagai penghasilan di SPT Tahunan karena sudah final. Tapi dokumen pajak tetap perlu disimpan sebagai bukti.' },
    ],
    references: ['PP No. 41 Tahun 1994 jo PP No. 14 Tahun 1997 tentang PPh atas saham', 'PP No. 131 Tahun 2000 tentang pajak deposito'],
    relatedTools: ['pajak/tax-optimizer-pph21', 'pajak/zakat-tax-planner'],
  },
  {
    slug: 'zakat-tax-planner',
    kategori: 'pajak',
    nama: 'Zakat & Tax Planner',
    deskripsi: 'Hitung kewajiban zakat mal dan zakat penghasilan, serta hubungannya dengan pajak penghasilan.',
    keywords: ['zakat mal', 'zakat penghasilan', 'nisab zakat', 'zakat dan pajak', 'kalkulator zakat'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Penghasilan Bulanan', desc: 'Penghasilan bersih per bulan.' },
      { judul: 'Masukkan Total Harta', desc: 'Tabungan, investasi, dan emas yang dimiliki.' },
      { judul: 'Masukkan Utang', desc: 'Total utang yang harus dibayar (dikurangi dari harta).' },
      { judul: 'Masukkan Harga Emas', desc: 'Harga emas per gram untuk menghitung nisab.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan kewajiban zakat dan analisa prioritas pembayaran.' },
    ],
    faqs: [
      { q: 'Apakah zakat bisa dikurangkan dari pajak?', a: 'Ya, sesuai UU PPh pasal 9 ayat 1, zakat yang dibayarkan melalui BAZNAS atau LAZ resmi dapat dikurangkan dari penghasilan kena pajak.' },
      { q: 'Apa itu nisab?', a: 'Nisab adalah batas minimum harta yang wajib dizakati. Nisab zakat mal setara 85 gram emas. Zakat penghasilan nisabnya setara 520 kg beras atau 85 gram emas per tahun.' },
    ],
    references: ['Fatwa MUI No. 3/2003 tentang Zakat Penghasilan', 'UU No. 23 Tahun 2011 tentang Pengelolaan Zakat'],
    relatedTools: ['pajak/tax-optimizer-pph21', 'pajak/investment-tax-report-generator'],
  },
  {
    slug: 'umkm-tax-estimator',
    kategori: 'pajak',
    nama: 'UMKM Tax Estimator',
    deskripsi: 'Estimasi PPh Final 0.5% untuk UMKM dan cek apakah omzet sudah melewati batas bebas pajak Rp 500 juta.',
    keywords: ['pajak UMKM', 'PPh final UMKM', 'pajak 0.5%', 'omzet bebas pajak UMKM'],
    tipe: 'K+A',
    tombol: 'Estimasi',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Omzet per Bulan', desc: 'Rata-rata omzet usaha per bulan.' },
      { judul: 'Masukkan Bulan Berjalan', desc: 'Sudah berapa bulan usaha berjalan di tahun ini.' },
      { judul: 'Klik Estimasi', desc: 'Dapatkan estimasi PPh dan analisa posisi omzet.' },
    ],
    faqs: [
      { q: 'Siapa yang bisa menggunakan tarif PPh Final UMKM 0.5%?', a: 'WP Orang Pribadi dan Badan yang omzet setahunnya tidak melebihi Rp 4,8 miliar. Untuk WP OP, omzet hingga Rp 500 juta per tahun bebas pajak.' },
      { q: 'Apakah PPh Final UMKM perlu lapor SPT?', a: 'Ya, tetap wajib lapor SPT Tahunan. PPh Final 0.5% harus dilaporkan di SPT meskipun sudah dibayar setiap bulan.' },
    ],
    references: ['PP No. 55 Tahun 2022 tentang Penyesuaian Pengaturan di Bidang PPh', 'PMK No. 99/PMK.03/2018'],
    relatedTools: ['pajak/tax-optimizer-pph21', 'pajak/ppn-tracker'],
  },
  {
    slug: 'ppn-tracker',
    kategori: 'pajak',
    nama: 'PPN Tracker',
    deskripsi: 'Hitung PPN dari harga yang sudah atau belum termasuk PPN dengan tarif yang bisa disesuaikan.',
    keywords: ['kalkulator PPN', 'hitung PPN', 'harga termasuk PPN', 'nilai PPN', 'dasar pengenaan pajak'],
    tipe: 'K',
    tombol: 'Hitung',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga', desc: 'Harga barang atau jasa.' },
      { judul: 'Pilih Inklusif atau Eksklusif', desc: 'Inklusif: harga sudah termasuk PPN. Eksklusif: harga belum termasuk PPN.' },
      { judul: 'Masukkan Tarif PPN', desc: 'Tarif PPN standar 11%. Bisa disesuaikan untuk tarif khusus.' },
      { judul: 'Klik Hitung', desc: 'Dapatkan DPP, nilai PPN, dan harga total.' },
    ],
    faqs: [
      { q: 'Berapa tarif PPN di Indonesia?', a: 'Tarif PPN standar adalah 11% sejak April 2022 (naik dari 10%). Beberapa barang/jasa tertentu dikenakan tarif 0% (ekspor) atau dibebaskan PPN.' },
    ],
    references: ['UU HPP No. 7 Tahun 2021 tentang perubahan tarif PPN'],
    relatedTools: ['pajak/umkm-tax-estimator', 'pajak/tax-optimizer-pph21'],
  },

  // ══════════════════════════════════════════════
  // INVESTASI
  // ══════════════════════════════════════════════
  {
    slug: 'dca-simulator',
    kategori: 'investasi',
    nama: 'DCA Simulator',
    deskripsi: 'Simulasikan pertumbuhan investasi Dollar Cost Averaging dengan grafik proyeksi nilai portofolio.',
    keywords: ['DCA simulator', 'simulasi DCA', 'dollar cost averaging', 'proyeksi investasi reksa dana'],
    tipe: 'S+G',
    tombol: 'Simulasikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Tentukan Investasi per Periode', desc: 'Jumlah rupiah yang diinvestasikan setiap bulan atau minggu.' },
      { judul: 'Masukkan Durasi', desc: 'Berapa bulan rencana investasi.' },
      { judul: 'Tentukan Estimasi Return', desc: 'Return tahunan yang diharapkan dalam persentase.' },
      { judul: 'Pilih Frekuensi', desc: 'Bulanan, mingguan, atau tahunan.' },
      { judul: 'Klik Simulasikan', desc: 'Lihat grafik pertumbuhan dan rincian nilai per tahun.' },
    ],
    faqs: [
      { q: 'Apa itu DCA dan mengapa efektif?', a: 'DCA adalah strategi investasi rutin dengan jumlah tetap terlepas kondisi pasar. Saat harga turun kamu beli lebih banyak unit, saat naik lebih sedikit — menghasilkan harga rata-rata beli yang lebih rendah dari rata-rata harga pasar.' },
      { q: 'Return berapa yang realistis untuk reksa dana saham?', a: 'Reksa dana saham Indonesia secara historis memberikan return 12–18% per tahun dalam jangka panjang (5–10 tahun). Namun ini tidak dijamin dan bisa sangat bervariasi per tahun.' },
    ],
    references: ['OJK — Laporan Perkembangan Industri Reksa Dana (2023)', 'Bursa Efek Indonesia — Indeks Statistik (2024)'],
    relatedTools: ['investasi/gold-dca-simulator', 'kripto/crypto-dca-simulator', 'personal-finance/savings-growth-simulator'],
  },
  {
    slug: 'sbn-maturity-planner',
    kategori: 'investasi',
    nama: 'SBN Maturity Planner',
    deskripsi: 'Rencanakan investasi Surat Berharga Negara (ORI, SBR, Sukuk) dan hitung imbal hasil bersih.',
    keywords: ['SBN', 'ORI', 'SBR', 'sukuk ritel', 'obligasi negara', 'investasi SBN', 'kupon SBN'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Nominal Investasi', desc: 'Jumlah uang yang diinvestasikan dalam SBN.' },
      { judul: 'Masukkan Kupon', desc: 'Persentase kupon tahunan sesuai seri SBN yang dipilih.' },
      { judul: 'Masukkan Tenor', desc: 'Jangka waktu SBN dalam tahun.' },
      { judul: 'Masukkan Pajak Kupon', desc: 'Pajak atas kupon SBN — standar 10% untuk WP dalam negeri.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan kupon bersih, total return, dan analisa kelayakan.' },
    ],
    faqs: [
      { q: 'Apa perbedaan ORI dan SBR?', a: 'ORI (Obligasi Ritel Indonesia) adalah obligasi dengan kupon tetap yang bisa diperdagangkan di pasar sekunder. SBR (Savings Bond Ritel) menggunakan kupon floating yang mengikuti BI Rate, tidak bisa diperdagangkan tapi bisa dicairkan sebagian setelah periode tertentu.' },
      { q: 'Apakah SBN lebih aman dari deposito?', a: 'Ya. SBN dijamin penuh oleh pemerintah Indonesia tanpa batas nominal, berbeda dari deposito yang dijamin LPS hanya hingga Rp 2 miliar.' },
    ],
    references: ['Kementerian Keuangan RI — Surat Utang Negara', 'DJPPR Kemenkeu — Statistik Utang Pemerintah (2024)'],
    relatedTools: ['investasi/bond-yield-analyzer', 'investasi/coupon-income-planner'],
  },
  {
    slug: 'coupon-income-planner',
    kategori: 'investasi',
    nama: 'Coupon Income Planner',
    deskripsi: 'Rencanakan pendapatan kupon dari portofolio obligasi dengan visualisasi arus kas per tahun.',
    keywords: ['kupon obligasi', 'pendapatan obligasi', 'coupon income', 'arus kas obligasi'],
    tipe: 'K+G',
    tombol: 'Hitung',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Nominal Obligasi', desc: 'Nilai nominal/face value obligasi yang dimiliki.' },
      { judul: 'Masukkan Kupon', desc: 'Persentase kupon per tahun.' },
      { judul: 'Pilih Frekuensi Pembayaran', desc: 'Tahunan, semester (2x), kuartalan (4x), atau bulanan (12x).' },
      { judul: 'Masukkan Pajak & Tenor', desc: 'Tarif pajak kupon dan jangka waktu obligasi.' },
      { judul: 'Klik Hitung', desc: 'Dapatkan jadwal kupon, total pendapatan, dan grafik arus kas.' },
    ],
    faqs: [
      { q: 'Obligasi apa yang membayar kupon bulanan?', a: 'Kebanyakan obligasi pemerintah dan korporasi Indonesia membayar kupon semester (setiap 6 bulan). Beberapa reksa dana pendapatan tetap bisa mendistribusikan hasil bulanan.' },
    ],
    references: ['BEI — Panduan Investasi Obligasi', 'OJK — Buku Panduan Investasi Pasar Modal'],
    relatedTools: ['investasi/sbn-maturity-planner', 'investasi/bond-yield-analyzer', 'investasi/dividend-income-projector'],
  },
  {
    slug: 'bond-yield-analyzer',
    kategori: 'investasi',
    nama: 'Bond Yield Analyzer',
    deskripsi: 'Analisa yield obligasi termasuk current yield, yield to maturity (YTM), dan status premium/diskon.',
    keywords: ['yield to maturity', 'YTM', 'current yield', 'analisa obligasi', 'harga obligasi'],
    tipe: 'K+A',
    tombol: 'Analisa Yield',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Beli', desc: 'Harga aktual pembelian obligasi per lembar.' },
      { judul: 'Masukkan Nominal', desc: 'Nilai nominal/face value obligasi.' },
      { judul: 'Masukkan Kupon & Tenor', desc: 'Persentase kupon dan sisa tenor dalam tahun.' },
      { judul: 'Masukkan Pajak', desc: 'Tarif pajak atas kupon.' },
      { judul: 'Klik Analisa Yield', desc: 'Dapatkan current yield, YTM, status premium/diskon, dan analisa.' },
    ],
    faqs: [
      { q: 'Apa bedanya current yield dan YTM?', a: 'Current yield hanya memperhitungkan kupon dibagi harga saat ini. YTM (yield to maturity) memperhitungkan kupon DAN selisih antara harga beli dan nilai nominal saat jatuh tempo — lebih komprehensif untuk perbandingan obligasi.' },
      { q: 'Kapan obligasi diperdagangkan di atas nominal (premium)?', a: 'Saat suku bunga pasar turun di bawah kupon obligasi, harga obligasi naik di atas nominal (premium). Investor bersedia membayar lebih karena kupon obligasi lebih tinggi dari yield pasar.' },
    ],
    references: ['Frank J. Fabozzi — The Handbook of Fixed Income Securities (2005)', 'BEI — Panduan Investasi Obligasi'],
    relatedTools: ['investasi/sbn-maturity-planner', 'investasi/coupon-income-planner'],
  },
  {
    slug: 'gold-dca-simulator',
    kategori: 'investasi',
    nama: 'Gold DCA Simulator',
    deskripsi: 'Simulasikan akumulasi gram emas dari investasi DCA rutin dan proyeksi nilai di berbagai target harga.',
    keywords: ['DCA emas', 'tabungan emas', 'simulasi investasi emas', 'akumulasi gram emas'],
    tipe: 'S+G',
    tombol: 'Simulasikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Tentukan Investasi per Bulan', desc: 'Jumlah rupiah yang dialokasikan untuk beli emas setiap bulan.' },
      { judul: 'Masukkan Durasi', desc: 'Berapa bulan rencana akumulasi emas.' },
      { judul: 'Masukkan Harga Emas Sekarang', desc: 'Harga emas saat ini per gram (Antam atau LM).' },
      { judul: 'Masukkan Target Harga', desc: 'Proyeksi harga emas yang kamu targetkan.' },
      { judul: 'Klik Simulasikan', desc: 'Lihat total gram terkumpul dan nilai di target harga.' },
    ],
    faqs: [
      { q: 'Platform apa yang bisa digunakan untuk DCA emas?', a: 'Pegadaian Digital (Tabungan Emas), Tokopedia Emas, Shopee Emas, Treasury, dan Antam. Semuanya menawarkan pembelian emas digital mulai dari nominal sangat kecil (< Rp 10.000).' },
      { q: 'Apakah emas digital sama dengan emas fisik?', a: 'Emas digital dijamin oleh emas fisik yang disimpan di vault. Bisa dicetak menjadi fisik dengan minimum tertentu (biasanya 1 gram untuk Antam/LM). Cek biaya cetak sebelum memilih platform.' },
    ],
    references: ['World Gold Council — Gold Demand Trends (2024)', 'Antam — Statistik Harga Emas LM'],
    relatedTools: ['investasi/gold-vs-inflation-analyzer', 'investasi/dca-simulator'],
  },
  {
    slug: 'gold-vs-inflation-analyzer',
    kategori: 'investasi',
    nama: 'Gold vs Inflation Analyzer',
    deskripsi: 'Bandingkan apakah emas berhasil mengalahkan inflasi dan lindungi daya beli investasi kamu.',
    keywords: ['emas vs inflasi', 'lindung nilai emas', 'inflation hedge emas', 'return riil emas'],
    tipe: 'A+G',
    tombol: 'Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Jumlah Investasi', desc: 'Nilai investasi dalam Rupiah.' },
      { judul: 'Tentukan Periode', desc: 'Berapa tahun periode analisa.' },
      { judul: 'Masukkan Return Emas', desc: 'Estimasi return emas per tahun — historis Indonesia sekitar 8–12% per tahun.' },
      { judul: 'Masukkan Inflasi', desc: 'Estimasi inflasi tahunan — target BI adalah 2–4%.' },
      { judul: 'Klik Analisa', desc: 'Lihat perbandingan nilai riil emas vs daya beli uang dan grafik.' },
    ],
    faqs: [
      { q: 'Apakah emas selalu mengalahkan inflasi?', a: 'Dalam jangka panjang (10+ tahun), emas secara historis mengalahkan inflasi Indonesia. Namun dalam jangka pendek bisa sangat volatile — ada tahun emas melemah signifikan.' },
    ],
    references: ['World Gold Council — Gold and Inflation (2023)', 'BPS — Laporan Inflasi Indonesia'],
    relatedTools: ['investasi/gold-dca-simulator', 'personal-finance/inflation-guard'],
  },
  {
    slug: 'dividend-income-projector',
    kategori: 'investasi',
    nama: 'Dividend Income Projector',
    deskripsi: 'Proyeksikan pendapatan dividen dan pertumbuhannya selama bertahun-tahun dari saham dividen.',
    keywords: ['proyeksi dividen', 'passive income dividen', 'dividend yield', 'pendapatan dividen saham'],
    tipe: 'S+G',
    tombol: 'Proyeksikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Jumlah & Harga Saham', desc: 'Jumlah lembar saham yang dimiliki dan harga per lembar saat ini.' },
      { judul: 'Masukkan Dividend Yield', desc: 'Persentase dividen terhadap harga saham per tahun.' },
      { judul: 'Masukkan Pertumbuhan Dividen', desc: 'Estimasi kenaikan dividen per tahun — perusahaan bagus bisa 5–10% per tahun.' },
      { judul: 'Tentukan Periode', desc: 'Berapa tahun proyeksi yang diinginkan.' },
      { judul: 'Klik Proyeksikan', desc: 'Lihat grafik pertumbuhan dividen dan total kumulatif.' },
    ],
    faqs: [
      { q: 'Saham apa yang cocok untuk strategi dividen?', a: 'Cari saham dengan dividend yield 3–8%, pertumbuhan dividen konsisten 5+ tahun terakhir, payout ratio 40–70%, dan bisnis yang stabil. Di IDX: perbankan besar, BUMN, consumer goods.' },
    ],
    references: ['BEI — Data Dividen Emiten (2024)', 'Jeremy Siegel — Stocks for the Long Run (2014)'],
    relatedTools: ['investasi/drip-simulator', 'investasi/coupon-income-planner', 'saham/entry-price-optimizer'],
  },
  {
    slug: 'drip-simulator',
    kategori: 'investasi',
    nama: 'DRIP Simulator',
    deskripsi: 'Simulasikan dampak reinvestasi dividen (DRIP) vs tidak reinvestasi terhadap pertumbuhan portofolio.',
    keywords: ['DRIP', 'dividend reinvestment', 'reinvestasi dividen', 'compound dividen', 'simulasi DRIP'],
    tipe: 'S+G',
    tombol: 'Simulasikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Jumlah Saham Awal', desc: 'Jumlah lembar saham yang dimiliki saat ini.' },
      { judul: 'Masukkan Harga & Dividend Yield', desc: 'Harga saham saat ini dan yield dividen.' },
      { judul: 'Masukkan Pertumbuhan Harga', desc: 'Estimasi kenaikan harga saham per tahun.' },
      { judul: 'Tentukan Periode', desc: 'Berapa tahun periode simulasi.' },
      { judul: 'Klik Simulasikan', desc: 'Bandingkan nilai portofolio dengan dan tanpa DRIP.' },
    ],
    faqs: [
      { q: 'Apa itu DRIP?', a: 'DRIP (Dividend Reinvestment Plan) adalah strategi menggunakan seluruh dividen yang diterima untuk membeli saham tambahan secara otomatis. Efek compound-nya sangat signifikan dalam jangka panjang.' },
    ],
    references: ['Jeremy Siegel — The Future for Investors (2005)'],
    relatedTools: ['investasi/dividend-income-projector', 'investasi/dca-simulator'],
  },

  // ══════════════════════════════════════════════
  // PERSONAL FINANCE
  // ══════════════════════════════════════════════
  {
    slug: 'wealth-freedom-planner',
    kategori: 'personal-finance',
    nama: 'Wealth Freedom Planner',
    deskripsi: 'Hitung FIRE number dan simulasikan berapa lama mencapai kebebasan finansial berdasarkan kondisi keuanganmu.',
    keywords: ['FIRE', 'financial independence', 'kebebasan finansial', 'FIRE number', 'pensiun dini'],
    tipe: 'S+A+G',
    tombol: 'Hitung FIRE Number',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Pengeluaran Bulanan', desc: 'Total pengeluaran hidup per bulan yang ingin dipertahankan saat FIRE.' },
      { judul: 'Masukkan Tabungan Sekarang', desc: 'Total aset investasi yang sudah dimiliki.' },
      { judul: 'Masukkan Investasi per Bulan', desc: 'Jumlah yang rutin diinvestasikan setiap bulan.' },
      { judul: 'Masukkan Return & Inflasi', desc: 'Estimasi return investasi dan inflasi tahunan.' },
      { judul: 'Klik Hitung FIRE Number', desc: 'Dapatkan FIRE number, timeline, dan simulasi grafik.' },
    ],
    faqs: [
      { q: 'Apa itu 4% Rule yang digunakan untuk FIRE number?', a: 'The 4% Rule (Aturan 4%) menyatakan bahwa kamu bisa menarik 4% dari portofolio investasi setiap tahun tanpa kehabisan uang dalam 30 tahun. Artinya FIRE Number = pengeluaran tahunan / 4%.' },
      { q: 'Berapa FIRE number yang realistis untuk Indonesia?', a: 'Dengan pengeluaran Rp 10 juta per bulan, FIRE number adalah Rp 3 miliar. Dengan pengeluaran Rp 5 juta per bulan, FIRE number adalah Rp 1,5 miliar. Sesuaikan dengan gaya hidup yang diinginkan.' },
    ],
    references: ['William Bengen — Determining Withdrawal Rates Using Historical Data (1994)', 'Mr. Money Mustache — Early Retirement (2012)'],
    relatedTools: ['personal-finance/savings-growth-simulator', 'personal-finance/inflation-guard', 'personal-finance/net-worth-tracker'],
  },
  {
    slug: 'emergency-shield-builder',
    kategori: 'personal-finance',
    nama: 'Emergency Shield Builder',
    deskripsi: 'Hitung target dana darurat yang tepat dan berapa lama waktu yang dibutuhkan untuk mencapainya.',
    keywords: ['dana darurat', 'emergency fund', 'berapa dana darurat', 'target dana darurat', 'tabungan darurat'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Pengeluaran Wajib', desc: 'Total pengeluaran wajib per bulan (makan, sewa, cicilan, tagihan).' },
      { judul: 'Pilih Target Bulan', desc: '3 bulan untuk karyawan tetap, 6 bulan untuk freelancer, 9–12 bulan untuk pengusaha.' },
      { judul: 'Masukkan Tabungan Saat Ini', desc: 'Dana yang sudah tersedia untuk dana darurat.' },
      { judul: 'Masukkan Tabungan per Bulan', desc: 'Jumlah yang bisa disisihkan setiap bulan.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan target, kekurangan, timeline, dan strategi pengisian.' },
    ],
    faqs: [
      { q: 'Di mana sebaiknya menyimpan dana darurat?', a: 'Reksa dana pasar uang adalah pilihan terbaik: return 4–6% per tahun, bisa dicairkan dalam 1–2 hari kerja, risiko sangat rendah. Hindari deposito jangka panjang karena tidak bisa dicairkan sewaktu-waktu.' },
      { q: 'Apakah dana darurat harus terpisah dari tabungan biasa?', a: 'Wajib. Jika tercampur, kamu akan selalu merasa "ada uang" dan tergoda menggunakannya untuk non-darurat. Buka rekening atau akun reksa dana khusus hanya untuk dana darurat.' },
    ],
    references: ['Dave Ramsey — The Total Money Makeover (2003)', 'OJK — Panduan Perencanaan Keuangan Keluarga'],
    relatedTools: ['personal-finance/budget-architect', 'personal-finance/savings-growth-simulator'],
  },
  {
    slug: 'inflation-guard',
    kategori: 'personal-finance',
    nama: 'Inflation Guard',
    deskripsi: 'Visualisasikan penurunan daya beli akibat inflasi dan temukan instrumen investasi yang melindunginya.',
    keywords: ['inflasi', 'daya beli', 'inflasi Indonesia', 'lindung nilai inflasi', 'penurunan nilai uang'],
    tipe: 'A+G',
    tombol: 'Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Jumlah Uang', desc: 'Nilai uang yang ingin dianalisa penurunan daya belinya.' },
      { judul: 'Masukkan Estimasi Inflasi', desc: 'Target inflasi BI adalah 2–4% per tahun.' },
      { judul: 'Tentukan Periode', desc: 'Berapa tahun ke depan yang ingin dianalisa.' },
      { judul: 'Klik Analisa', desc: 'Lihat grafik penurunan daya beli dan rekomendasi instrumen pelindung.' },
    ],
    faqs: [
      { q: 'Berapa inflasi rata-rata Indonesia?', a: 'Inflasi Indonesia rata-rata 3–5% per tahun dalam dekade terakhir. Target BI adalah 2–4%. Pada 2022 inflasi sempat mencapai 5.5% akibat kenaikan harga energi global.' },
    ],
    references: ['BPS — Data Inflasi Indonesia (2024)', 'Bank Indonesia — Laporan Kebijakan Moneter'],
    relatedTools: ['investasi/gold-vs-inflation-analyzer', 'personal-finance/wealth-freedom-planner'],
  },
  {
    slug: 'budget-architect',
    kategori: 'personal-finance',
    nama: 'Budget Architect',
    deskripsi: 'Buat anggaran bulanan menggunakan aturan 50-30-20 dan analisa apakah komposisi pengeluaranmu sudah ideal.',
    keywords: ['budgeting', 'anggaran bulanan', 'aturan 50 30 20', 'keuangan pribadi', 'budget planning'],
    tipe: 'K+A',
    tombol: 'Buat Anggaran',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Penghasilan Bersih', desc: 'Take-home pay setelah pajak dan potongan wajib lainnya.' },
      { judul: 'Sesuaikan Persentase', desc: 'Default 50% kebutuhan, 30% keinginan, 20% tabungan. Bisa disesuaikan.' },
      { judul: 'Klik Buat Anggaran', desc: 'Dapatkan alokasi dalam rupiah dan analisa komposisi anggaran.' },
    ],
    faqs: [
      { q: 'Apakah aturan 50-30-20 berlaku untuk semua orang?', a: 'Tidak. Untuk penghasilan rendah, 50% mungkin tidak cukup untuk kebutuhan. Untuk penghasilan tinggi, 30% keinginan mungkin terlalu besar. Aturan ini adalah panduan awal, sesuaikan dengan kondisi nyata.' },
      { q: 'Apa yang masuk kategori "kebutuhan" vs "keinginan"?', a: 'Kebutuhan: makan, sewa, cicilan wajib, transportasi kerja, tagihan. Keinginan: hiburan, makan di luar, langganan streaming, liburan, gadget baru.' },
    ],
    references: ['Elizabeth Warren — All Your Worth: The Ultimate Lifetime Money Plan (2005)'],
    relatedTools: ['personal-finance/emergency-shield-builder', 'personal-finance/debt-destroyer', 'personal-finance/net-worth-tracker'],
  },
  {
    slug: 'debt-destroyer',
    kategori: 'personal-finance',
    nama: 'Debt Destroyer',
    deskripsi: 'Analisa strategi pelunasan utang terbaik: metode Avalanche (bunga tertinggi) vs Snowball (saldo terkecil).',
    keywords: ['lunasi utang', 'debt destroyer', 'avalanche method', 'snowball method', 'strategi bayar utang'],
    tipe: 'A+G',
    tombol: 'Analisa Utang',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Tambah Semua Utang', desc: 'Masukkan nama, saldo, bunga bulanan, dan cicilan minimum setiap utang.' },
      { judul: 'Masukkan Dana Ekstra', desc: 'Jumlah tambahan per bulan yang bisa dialokasikan untuk bayar utang lebih cepat.' },
      { judul: 'Klik Analisa Utang', desc: 'Dapatkan urutan pelunasan optimal, total bunga, dan visualisasi.' },
    ],
    faqs: [
      { q: 'Metode Avalanche atau Snowball yang lebih baik?', a: 'Secara matematis Avalanche lebih efisien (bayar lebih sedikit bunga). Tapi Snowball memberikan kemenangan psikologis lebih cepat yang membantu motivasi. Pilih sesuai tipe kepribadianmu.' },
      { q: 'Utang apa yang harus dilunasi pertama?', a: 'Prioritaskan utang dengan bunga tertinggi (kartu kredit 2–4% per bulan) sebelum utang berbunga rendah (KPR 8–11% per tahun). Perbedaan biaya bunganya sangat signifikan.' },
    ],
    references: ['Dave Ramsey — The Total Money Makeover (2003)', 'OJK — Panduan Kredit yang Sehat'],
    relatedTools: ['personal-finance/net-worth-tracker', 'personal-finance/budget-architect', 'kredit-properti/loan-true-cost-analyzer'],
  },
  {
    slug: 'net-worth-tracker',
    kategori: 'personal-finance',
    nama: 'Net Worth Tracker',
    deskripsi: 'Hitung net worth dan pantau komposisi aset vs liabilitas dengan visualisasi grafik yang jelas.',
    keywords: ['net worth', 'kekayaan bersih', 'total aset', 'liabilitas', 'tracker keuangan'],
    tipe: 'K+A+G',
    tombol: 'Hitung Net Worth',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Semua Aset', desc: 'Kas & tabungan, investasi, properti, kendaraan, dan aset lainnya.' },
      { judul: 'Masukkan Semua Liabilitas', desc: 'KPR, cicilan kendaraan, kartu kredit, KTA, dan utang lainnya.' },
      { judul: 'Klik Hitung Net Worth', desc: 'Dapatkan net worth, debt ratio, grafik komposisi, dan analisa kesehatan finansial.' },
    ],
    faqs: [
      { q: 'Berapa net worth yang "normal" untuk usia saya?', a: 'Panduan umum: net worth = usia × penghasilan bruto tahunan / 10. Misal usia 30 dengan gaji Rp 10 juta/bulan, target net worth Rp 360 juta. Ini bukan aturan pasti tapi panduan evaluasi.' },
    ],
    references: ['Thomas Stanley — The Millionaire Next Door (1996)', 'OJK — Panduan Perencanaan Keuangan Keluarga'],
    relatedTools: ['personal-finance/wealth-freedom-planner', 'personal-finance/budget-architect', 'personal-finance/debt-destroyer'],
  },
  {
    slug: 'savings-growth-simulator',
    kategori: 'personal-finance',
    nama: 'Savings Growth Simulator',
    deskripsi: 'Simulasikan pertumbuhan tabungan dengan berbagai instrumen dan visualisasi kekuatan compound interest.',
    keywords: ['simulasi tabungan', 'compound interest', 'bunga berbunga', 'pertumbuhan tabungan', 'kalkulator tabungan'],
    tipe: 'S+G',
    tombol: 'Simulasikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Tabungan Awal', desc: 'Jumlah yang sudah tersimpan saat ini.' },
      { judul: 'Masukkan Tabungan per Bulan', desc: 'Jumlah yang akan ditambahkan setiap bulan.' },
      { judul: 'Masukkan Return Tahunan', desc: 'Estimasi return instrumen yang dipilih per tahun.' },
      { judul: 'Tentukan Durasi', desc: 'Berapa tahun rencana menabung.' },
      { judul: 'Klik Simulasikan', desc: 'Lihat grafik pertumbuhan dan perbandingan total setor vs nilai akhir.' },
    ],
    faqs: [
      { q: 'Instrumen apa yang memberikan return 6% per tahun dengan risiko rendah?', a: 'Reksa dana pasar uang memberikan 4–6% per tahun dengan risiko sangat rendah. Obligasi ritel pemerintah (ORI, SBR) memberikan 6–7.5% dengan keamanan terjamin pemerintah.' },
    ],
    references: ['Albert Einstein (attributed) — Compound interest as eighth wonder of the world'],
    relatedTools: ['personal-finance/wealth-freedom-planner', 'personal-finance/goal-achiever-planner', 'investasi/dca-simulator'],
  },
  {
    slug: 'goal-achiever-planner',
    kategori: 'personal-finance',
    nama: 'Goal Achiever Planner',
    deskripsi: 'Hitung berapa yang perlu ditabung per bulan untuk mencapai target finansial dalam waktu tertentu.',
    keywords: ['target keuangan', 'goal achiever', 'menabung untuk target', 'financial goal planner'],
    tipe: 'K+A',
    tombol: 'Hitung Target',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Target Jumlah', desc: 'Berapa dana yang ingin dicapai (liburan, DP rumah, pendidikan, dll).' },
      { judul: 'Masukkan Tabungan Saat Ini', desc: 'Dana yang sudah tersedia untuk tujuan ini.' },
      { judul: 'Tentukan Waktu Target', desc: 'Berapa bulan atau tahun untuk mencapai target.' },
      { judul: 'Masukkan Return', desc: 'Estimasi return instrumen tabungan per tahun.' },
      { judul: 'Klik Hitung Target', desc: 'Dapatkan jumlah yang perlu ditabung per bulan dan analisa realistisitas target.' },
    ],
    faqs: [
      { q: 'Bagaimana jika jumlah per bulan yang dihasilkan terlalu besar?', a: 'Ada tiga opsi: perpanjang jangka waktu, naikkan return dengan instrumen lebih agresif, atau kurangi target. Sering kali kombinasi ketiga opsi ini memberikan angka yang lebih realistis.' },
    ],
    references: ['OJK — Panduan Perencanaan Keuangan Keluarga'],
    relatedTools: ['personal-finance/savings-growth-simulator', 'personal-finance/budget-architect'],
  },

  // ══════════════════════════════════════════════
  // KREDIT & PROPERTI
  // ══════════════════════════════════════════════
  {
    slug: 'loan-true-cost-analyzer',
    kategori: 'kredit-properti',
    nama: 'Loan True Cost Analyzer',
    deskripsi: 'Hitung total biaya sebenarnya dari pinjaman termasuk total bunga yang dibayar selama tenor.',
    keywords: ['total biaya pinjaman', 'bunga flat vs anuitas', 'true cost loan', 'biaya sebenarnya kredit'],
    tipe: 'K+A',
    tombol: 'Analisa Biaya',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Pokok Pinjaman', desc: 'Jumlah uang yang dipinjam.' },
      { judul: 'Masukkan Bunga Tahunan', desc: 'Tingkat bunga per tahun yang ditawarkan.' },
      { judul: 'Masukkan Tenor', desc: 'Jangka waktu pinjaman dalam bulan.' },
      { judul: 'Pilih Jenis Bunga', desc: 'Flat, efektif, atau anuitas — ketiganya menghasilkan total bayar berbeda.' },
      { judul: 'Klik Analisa Biaya', desc: 'Dapatkan cicilan, total bayar, total bunga, dan analisa perbandingan.' },
    ],
    faqs: [
      { q: 'Apa perbedaan bunga flat dan anuitas?', a: 'Bunga flat: cicilan tetap, tapi bunga dihitung dari pokok awal sehingga efektif rate-nya jauh lebih tinggi. Bunga anuitas/efektif: cicilan tetap, bunga dihitung dari saldo yang berkurang. Anuitas lebih transparan dan lebih murah.' },
      { q: 'Mengapa bunga flat terlihat lebih kecil tapi sebenarnya lebih mahal?', a: 'Bunga flat 10% setahun setara dengan bunga efektif 18–20% setahun. Bank sering mengiklankan bunga flat karena terlihat lebih rendah, padahal total bunga yang dibayar jauh lebih besar.' },
    ],
    references: ['BI — Peraturan tentang Transparansi Biaya Kredit', 'OJK — Panduan Kredit Konsumer'],
    relatedTools: ['kredit-properti/kpr-affordability-checker', 'kredit-properti/refinancing-decision-tool'],
  },
  {
    slug: 'refinancing-decision-tool',
    kategori: 'kredit-properti',
    nama: 'Refinancing Decision Tool',
    deskripsi: 'Analisa apakah refinancing KPR menguntungkan berdasarkan penghematan cicilan dan break-even point biaya.',
    keywords: ['refinancing KPR', 'takeover KPR', 'apakah refinancing menguntungkan', 'break even refinancing'],
    tipe: 'K+A',
    tombol: 'Analisa Refinancing',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Sisa Pokok & Tenor', desc: 'Saldo KPR yang tersisa dan tenor yang masih berjalan.' },
      { judul: 'Masukkan Bunga Lama', desc: 'Bunga KPR yang sedang berjalan saat ini.' },
      { judul: 'Masukkan Bunga Baru', desc: 'Bunga KPR baru yang ditawarkan oleh bank tujuan.' },
      { judul: 'Masukkan Biaya Refinancing', desc: 'Total biaya notaris, provisi, dan penalti pelunasan di bank lama.' },
      { judul: 'Klik Analisa Refinancing', desc: 'Dapatkan penghematan cicilan, break-even point, dan rekomendasi.' },
    ],
    faqs: [
      { q: 'Kapan saat yang tepat untuk refinancing?', a: 'Ideal saat: (1) bunga baru lebih rendah minimal 1.5–2%, (2) masih ada tenor panjang tersisa (minimal 5 tahun), (3) break-even biaya refinancing kurang dari 2 tahun.' },
      { q: 'Berapa biaya yang perlu diperhitungkan untuk refinancing?', a: 'Biaya notaris PPAT, biaya appraisal, provisi bank baru, dan penalti pelunasan di bank lama (biasanya 1–3% dari sisa pokok dalam 5 tahun pertama).' },
    ],
    references: ['BI — Statistik Perbankan Indonesia (2024)', 'OJK — Panduan KPR'],
    relatedTools: ['kredit-properti/kpr-affordability-checker', 'kredit-properti/loan-true-cost-analyzer'],
  },
  {
    slug: 'buy-vs-rent-analyzer',
    kategori: 'kredit-properti',
    nama: 'Buy vs Rent Analyzer',
    deskripsi: 'Analisa komprehensif apakah membeli atau menyewa properti lebih menguntungkan dalam jangka panjang.',
    keywords: ['beli vs sewa rumah', 'buy vs rent', 'lebih baik beli atau sewa properti', 'analisa properti'],
    tipe: 'A+G',
    tombol: 'Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Data Pembelian', desc: 'Harga properti, DP, bunga KPR, dan tenor.' },
      { judul: 'Masukkan Data Sewa', desc: 'Sewa bulanan saat ini dan estimasi kenaikan sewa tahunan.' },
      { judul: 'Masukkan Apresiasi Properti', desc: 'Estimasi kenaikan harga properti per tahun.' },
      { judul: 'Tentukan Periode Analisa', desc: 'Berapa tahun ke depan yang ingin dibandingkan.' },
      { judul: 'Klik Analisa', desc: 'Lihat perbandingan biaya dan grafik akumulasi kekayaan.' },
    ],
    faqs: [
      { q: 'Faktor apa yang paling mempengaruhi keputusan beli vs sewa?', a: 'Apresiasi properti, selisih antara cicilan KPR dan sewa, dan berapa lama kamu berencana tinggal di lokasi tersebut. Jika kurang dari 5 tahun, sewa biasanya lebih efisien.' },
    ],
    references: ['Bank Indonesia — Survei Harga Properti Residensial (2024)'],
    relatedTools: ['kredit-properti/kpr-affordability-checker', 'kredit-properti/rental-yield-analyzer'],
  },
  {
    slug: 'kpr-affordability-checker',
    kategori: 'kredit-properti',
    nama: 'KPR Affordability Checker',
    deskripsi: 'Cek kemampuan cicilan KPR berdasarkan penghasilan, cicilan existing, dan kondisi keuangan saat ini.',
    keywords: ['kemampuan KPR', 'KPR affordability', 'cicilan KPR berapa', 'harga rumah yang bisa dijangkau', 'DTI KPR'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Penghasilan Bersih', desc: 'Take-home pay per bulan setelah pajak dan potongan.' },
      { judul: 'Masukkan Cicilan Lain', desc: 'Total cicilan yang sudah ada (motor, kartu kredit, KTA).' },
      { judul: 'Tentukan Bunga & Tenor', desc: 'Bunga KPR yang ditawarkan dan jangka waktu yang diinginkan.' },
      { judul: 'Tentukan Down Payment', desc: 'Persentase DP yang direncanakan (minimum 10% untuk rumah pertama).' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan harga properti maksimum, cicilan, DP, dan analisa kondisi finansial.' },
    ],
    faqs: [
      { q: 'Berapa DTI yang aman untuk KPR?', a: 'Bank Indonesia merekomendasikan DTI maksimal 35% — artinya total cicilan tidak boleh lebih dari 35% penghasilan. Beberapa bank bisa sampai 40%, tapi 35% adalah zona aman yang direkomendasikan perencana keuangan.' },
      { q: 'Apakah penghasilan suami istri bisa digabung?', a: 'Ya, hampir semua bank menerima joint income untuk KPR bersama suami-istri. Ini meningkatkan kemampuan KPR secara signifikan. Pastikan keduanya hadir saat pengajuan.' },
      { q: 'Apa itu KPR Subsidi FLPP?', a: 'Fasilitas Likuiditas Pembiayaan Perumahan — program KPR pemerintah dengan bunga fixed 5% per tahun untuk MBR (Masyarakat Berpenghasilan Rendah) dengan batas penghasilan dan harga properti tertentu.' },
    ],
    references: ['BI — Peraturan Bank Indonesia tentang LTV KPR', 'Kementerian PUPR — Statistik Perumahan (2024)', 'BTN — Laporan Tahunan (2024)'],
    relatedTools: ['kredit-properti/loan-true-cost-analyzer', 'kredit-properti/buy-vs-rent-analyzer', 'kredit-properti/refinancing-decision-tool'],
  },
  {
    slug: 'rental-yield-analyzer',
    kategori: 'kredit-properti',
    nama: 'Rental Yield Analyzer',
    deskripsi: 'Analisa yield sewa properti — gross yield, net yield, dan total return termasuk apresiasi nilai properti.',
    keywords: ['rental yield', 'yield properti', 'investasi properti', 'gross yield', 'net yield properti'],
    tipe: 'K+A',
    tombol: 'Analisa Yield',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Properti', desc: 'Harga beli properti yang dimiliki atau dianalisa.' },
      { judul: 'Masukkan Sewa per Bulan', desc: 'Estimasi sewa yang bisa diperoleh per bulan.' },
      { judul: 'Masukkan Biaya Tahunan', desc: 'Total biaya perawatan, pajak, dan manajemen per tahun.' },
      { judul: 'Masukkan Apresiasi & Periode', desc: 'Estimasi kenaikan harga properti per tahun dan periode analisa.' },
      { judul: 'Klik Analisa Yield', desc: 'Dapatkan gross yield, net yield, total return, dan analisa kelayakan.' },
    ],
    faqs: [
      { q: 'Berapa gross yield properti yang dianggap bagus?', a: 'Gross yield di atas 8% dianggap sangat baik. 5–8% bagus. 3–5% cukup. Di bawah 3% perlu pertimbangan ulang kecuali apresiasi nilai propertinya sangat tinggi.' },
      { q: 'Apa perbedaan gross yield dan net yield?', a: 'Gross yield: sewa tahunan / harga properti. Net yield: (sewa - biaya operasional) / harga properti. Net yield lebih akurat karena memperhitungkan biaya nyata.' },
    ],
    references: ['Bank Indonesia — Survei Harga Properti Residensial (2024)', 'JLL Indonesia — Property Market Overview (2024)'],
    relatedTools: ['kredit-properti/property-investment-analyzer', 'kredit-properti/buy-vs-rent-analyzer'],
  },
  {
    slug: 'property-investment-analyzer',
    kategori: 'kredit-properti',
    nama: 'Property Investment Analyzer',
    deskripsi: 'Analisa komprehensif kelayakan investasi properti: cash flow, cap rate, cash-on-cash return, dan proyeksi.',
    keywords: ['investasi properti', 'cash flow properti', 'cap rate', 'cash on cash return', 'analisa properti investasi'],
    tipe: 'K+A+G',
    tombol: 'Analisa Investasi',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Data Pembelian', desc: 'Harga beli, DP, bunga KPR, dan tenor.' },
      { judul: 'Masukkan Data Sewa', desc: 'Proyeksi sewa bulanan dan biaya operasional bulanan.' },
      { judul: 'Masukkan Apresiasi', desc: 'Estimasi kenaikan nilai properti per tahun.' },
      { judul: 'Tentukan Periode Analisa', desc: 'Berapa tahun horizon investasi.' },
      { judul: 'Klik Analisa Investasi', desc: 'Dapatkan cash flow, cap rate, CoC return, grafik proyeksi, dan analisa.' },
    ],
    faqs: [
      { q: 'Apa itu cap rate?', a: 'Capitalization Rate = Net Operating Income / Harga Properti. Cap rate 7% berarti properti menghasilkan 7% dari harganya dalam pendapatan bersih per tahun. Semakin tinggi cap rate, semakin menguntungkan.' },
      { q: 'Cash flow negatif apakah selalu buruk?', a: 'Tidak selalu. Cash flow negatif kecil bisa diterima jika apresiasi properti sangat tinggi. Namun untuk properti investasi murni, cash flow positif dari hari pertama adalah indikator kesehatan investasi.' },
    ],
    references: ['Brandon Turner — The Book on Rental Property Investing (2015)', 'Bank Indonesia — Survei Properti Komersial (2024)'],
    relatedTools: ['kredit-properti/rental-yield-analyzer', 'kredit-properti/buy-vs-rent-analyzer'],
  },

  // ══════════════════════════════════════════════
  // SAHAM
  // ══════════════════════════════════════════════
  {
    slug: 'averaging-strategy-builder',
    kategori: 'saham',
    nama: 'Averaging Strategy Builder',
    deskripsi: 'Hitung harga rata-rata setelah menambah posisi saham dan analisa apakah strategi averaging worth it.',
    keywords: ['averaging saham', 'average down', 'average up', 'harga rata-rata saham', 'strategi averaging IDX'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Posisi Awal', desc: 'Harga beli pertama dan jumlah lot.' },
      { judul: 'Masukkan Posisi Baru', desc: 'Harga beli tambahan dan jumlah lot yang akan ditambahkan.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan harga rata-rata baru, total lot, nilai posisi, dan analisa.' },
    ],
    faqs: [
      { q: 'Kapan averaging down layak dilakukan?', a: 'Averaging down layak jika: fundamental perusahaan masih baik, penurunan disebabkan sentimen pasar bukan masalah fundamental, dan kamu memiliki modal ekstra yang tidak akan dibutuhkan dalam waktu dekat.' },
      { q: 'Apa risiko utama averaging down?', a: 'Risiko terbesar adalah "catching a falling knife" — terus averaging pada saham yang fundamentalnya memang sedang memburuk. Selalu evaluasi ulang fundamental sebelum memutuskan averaging.' },
    ],
    references: ['Bursa Efek Indonesia — Panduan Investasi Saham', 'Lo, A.W. & MacKinlay, A.C. — A Non-random Walk Down Wall Street (1999)'],
    relatedTools: ['saham/entry-price-optimizer', 'saham/break-even-analyzer'],
  },
  {
    slug: 'entry-price-optimizer',
    kategori: 'saham',
    nama: 'Entry Price Optimizer',
    deskripsi: 'Optimalkan harga dan jumlah lot entry saham berdasarkan risk/reward ratio dan modal berisiko.',
    keywords: ['entry saham', 'harga entry optimal', 'lot optimal saham', 'risk reward saham IDX'],
    tipe: 'K+A',
    tombol: 'Optimalkan Entry',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Target Entry', desc: 'Harga per lembar saham yang direncanakan.' },
      { judul: 'Masukkan Stop Loss %', desc: 'Persentase penurunan dari entry sebagai batas cut loss.' },
      { judul: 'Masukkan Target Profit %', desc: 'Persentase kenaikan dari entry sebagai target take profit.' },
      { judul: 'Masukkan Modal & Risiko', desc: 'Total modal dan persentase maksimum yang dirisikoan per trade.' },
      { judul: 'Klik Optimalkan Entry', desc: 'Dapatkan lot optimal, level SL/TP, R/R ratio, dan analisa.' },
    ],
    faqs: [
      { q: 'Mengapa lot optimal sering lebih kecil dari yang diinginkan?', a: 'Tool menghitung lot berdasarkan risiko modal yang ditetapkan — bukan keinginan. Jika lot terlalu kecil, kemungkinan stop loss terlalu jauh atau modal berisiko terlalu kecil. Pertimbangkan perbesar risiko atau perkecil stop loss.' },
      { q: 'Apakah stop loss harus selalu dieksekusi?', a: 'Ya. Stop loss adalah perlindungan modal, bukan sekadar rencana. Tidak menjalankan stop loss adalah salah satu penyebab utama kerugian besar dalam trading saham.' },
    ],
    references: ['William O\'Neil — How to Make Money in Stocks (2009)', 'BEI — Panduan Trading Saham'],
    relatedTools: ['saham/averaging-strategy-builder', 'saham/break-even-analyzer', 'trading/risk-manager'],
  },
  {
    slug: 'break-even-analyzer',
    kategori: 'saham',
    nama: 'Break-even Analyzer',
    deskripsi: 'Hitung harga jual minimum untuk balik modal saham termasuk semua biaya transaksi dan fee broker.',
    keywords: ['break even saham', 'harga jual break even', 'biaya trading saham', 'fee broker saham IDX'],
    tipe: 'K',
    tombol: 'Hitung',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Beli', desc: 'Harga per lembar saham yang dibeli.' },
      { judul: 'Masukkan Jumlah Lot', desc: 'Jumlah lot yang dibeli (1 lot = 100 lembar).' },
      { judul: 'Masukkan Fee Beli', desc: 'Fee broker untuk transaksi beli — rata-rata 0.1–0.15%.' },
      { judul: 'Masukkan Fee Jual', desc: 'Fee broker untuk transaksi jual + pajak — rata-rata 0.25–0.30%.' },
      { judul: 'Klik Hitung', desc: 'Dapatkan harga jual minimum break-even.' },
    ],
    faqs: [
      { q: 'Berapa fee trading saham di IDX?', a: 'Fee beli umumnya 0.1–0.15%, fee jual 0.25–0.30% (sudah termasuk PPh final 0.1%). Total biaya bolak-balik sekitar 0.35–0.45% dari nilai transaksi.' },
    ],
    references: ['BEI — Ketentuan Biaya Transaksi Saham'],
    relatedTools: ['saham/averaging-strategy-builder', 'saham/entry-price-optimizer'],
  },

  // ══════════════════════════════════════════════
  // KRIPTO
  // ══════════════════════════════════════════════
  {
    slug: 'crypto-dca-simulator',
    kategori: 'kripto',
    nama: 'Crypto DCA Simulator',
    deskripsi: 'Simulasikan akumulasi koin kripto dari investasi DCA rutin dan proyeksi nilai di berbagai target harga.',
    keywords: ['DCA kripto', 'DCA bitcoin', 'simulasi DCA crypto', 'akumulasi bitcoin', 'investasi kripto rutin'],
    tipe: 'S+G',
    tombol: 'Simulasikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Tentukan Investasi per Periode', desc: 'Jumlah rupiah yang diinvestasikan setiap periode.' },
      { judul: 'Masukkan Jumlah Periode', desc: 'Berapa bulan rencana DCA kripto.' },
      { judul: 'Masukkan Harga Sekarang', desc: 'Harga kripto saat ini dalam Rupiah.' },
      { judul: 'Masukkan Target Harga', desc: 'Proyeksi harga yang kamu targetkan.' },
      { judul: 'Klik Simulasikan', desc: 'Lihat total koin terkumpul dan nilai di target harga.' },
    ],
    faqs: [
      { q: 'Platform kripto apa yang terdaftar resmi di Indonesia?', a: 'Platform yang diawasi Bappebti antara lain: Indodax, Pintu, Tokocrypto, Rekeningku, Luno, dan beberapa lainnya. Selalu gunakan platform terdaftar untuk keamanan dana.' },
      { q: 'Berapa alokasi kripto yang wajar dalam portofolio?', a: 'Untuk investor moderat, maksimal 5–10% dari total portofolio. Kripto adalah aset berisiko tinggi yang bisa turun 70–80% dalam bear market.' },
    ],
    references: ['Bappebti — Daftar Aset Kripto yang Diperdagangkan (2024)', 'CoinMarketCap — Bitcoin Historical Data'],
    relatedTools: ['investasi/dca-simulator', 'kripto/crypto-risk-manager'],
  },
  {
    slug: 'staking-reward-projector',
    kategori: 'kripto',
    nama: 'Staking Reward Projector',
    deskripsi: 'Proyeksikan reward staking kripto dengan perbandingan compound vs non-compound dalam berbagai periode.',
    keywords: ['staking kripto', 'staking reward', 'APY staking', 'proyeksi staking', 'compound staking'],
    tipe: 'S+G',
    tombol: 'Proyeksikan',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Jumlah Koin', desc: 'Total koin yang di-stake.' },
      { judul: 'Masukkan Harga Koin', desc: 'Harga koin saat ini dalam Rupiah.' },
      { judul: 'Masukkan APY', desc: 'Annual Percentage Yield dari platform staking yang dipilih.' },
      { judul: 'Tentukan Periode & Mode', desc: 'Berapa hari staking dan pilih compound atau non-compound.' },
      { judul: 'Klik Proyeksikan', desc: 'Lihat proyeksi reward dan perbandingan compound vs non-compound.' },
    ],
    faqs: [
      { q: 'Apa risiko staking kripto?', a: 'Risiko utama: (1) Harga koin bisa turun lebih cepat dari reward yang dikumpulkan, (2) Platform staking bisa collapse (FTX 2022 adalah contoh), (3) Beberapa staking mengharuskan lock-up period sehingga tidak bisa dijual saat harga turun.' },
      { q: 'APY staking berapa yang realistis?', a: 'APY 5–12% adalah wajar untuk koin besar seperti ETH dan SOL. APY di atas 20–50% biasanya mengandung risiko sangat tinggi atau tidak berkelanjutan.' },
    ],
    references: ['Ethereum Foundation — Staking Overview (2024)', 'Bappebti — Panduan Aset Kripto'],
    relatedTools: ['kripto/crypto-dca-simulator', 'kripto/crypto-risk-manager'],
  },
  {
    slug: 'crypto-risk-manager',
    kategori: 'kripto',
    nama: 'Crypto Risk Manager',
    deskripsi: 'Hitung ukuran posisi kripto yang aman berdasarkan modal dan persentase risiko per trade.',
    keywords: ['crypto risk manager', 'position sizing kripto', 'risiko trading kripto', 'manajemen risiko bitcoin'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Modal Trading', desc: 'Total modal yang dialokasikan untuk trading kripto.' },
      { judul: 'Tentukan % Risiko', desc: 'Persentase modal yang berani dirisikoan per trade — maksimal 2–5%.' },
      { judul: 'Masukkan Harga Entry & Stop Loss', desc: 'Harga entry yang direncanakan dan level stop loss.' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan jumlah koin optimal, nilai posisi, dan analisa.' },
    ],
    faqs: [
      { q: 'Berapa risiko per trade yang wajar untuk kripto?', a: 'Karena volatilitas kripto jauh lebih tinggi dari forex atau saham, disarankan risiko 1–2% per trade. Dengan 2%, kamu butuh 50 loss beruntun untuk kehilangan modal — cukup buffer untuk strategi yang solid.' },
    ],
    references: ['Van K. Tharp — Trade Your Way to Financial Freedom (1998)'],
    relatedTools: ['kripto/liquidation-price-analyzer', 'kripto/funding-rate-cost-estimator', 'trading/risk-manager'],
  },
  {
    slug: 'liquidation-price-analyzer',
    kategori: 'kripto',
    nama: 'Liquidation Price Analyzer',
    deskripsi: 'Hitung harga likuidasi posisi leverage kripto dan analisa seberapa dekat risiko dari harga saat ini.',
    keywords: ['harga likuidasi kripto', 'liquidation price', 'leverage kripto', 'futures kripto', 'risiko likuidasi'],
    tipe: 'K+A',
    tombol: 'Analisa Risiko',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Harga Entry', desc: 'Harga di mana posisi dibuka.' },
      { judul: 'Masukkan Leverage', desc: 'Leverage yang digunakan (misal 5x, 10x, 20x).' },
      { judul: 'Masukkan Maintenance Margin', desc: 'Biasanya 0.5–1% tergantung exchange.' },
      { judul: 'Pilih Long atau Short', desc: 'Arah posisi yang diambil.' },
      { judul: 'Klik Analisa Risiko', desc: 'Dapatkan harga likuidasi, jarak dalam persen, dan analisa risiko.' },
    ],
    faqs: [
      { q: 'Mengapa leverage 20x sangat berbahaya untuk kripto?', a: 'Leverage 20x berarti harga hanya perlu turun 5% untuk likuidasi. Kripto reguler bisa bergerak 5–10% dalam hitungan menit. Bahkan trader profesional jarang menggunakan lebih dari 3–5x leverage untuk kripto.' },
    ],
    references: ['Binance Academy — Liquidation Guide', 'CoinGlass — Liquidation Data'],
    relatedTools: ['kripto/crypto-risk-manager', 'kripto/funding-rate-cost-estimator'],
  },
  {
    slug: 'funding-rate-cost-estimator',
    kategori: 'kripto',
    nama: 'Funding Rate Cost Estimator',
    deskripsi: 'Hitung total biaya funding rate untuk posisi futures kripto dan analisa apakah worth it mempertahankan posisi.',
    keywords: ['funding rate kripto', 'biaya futures kripto', 'funding fee calculator', 'perpetual futures kripto'],
    tipe: 'K+A',
    tombol: 'Hitung & Analisa',
    dateVerified: '2024-11',
    steps: [
      { judul: 'Masukkan Nilai Posisi', desc: 'Total nilai posisi futures dalam Rupiah.' },
      { judul: 'Masukkan Funding Rate', desc: 'Funding rate saat ini dalam persentase per periode (bisa dilihat di exchange).' },
      { judul: 'Masukkan Periode Ditahan', desc: 'Berapa hari rencana mempertahankan posisi.' },
      { judul: 'Masukkan Frekuensi Funding', desc: 'Berapa kali funding per hari — biasanya 3x (setiap 8 jam).' },
      { judul: 'Klik Hitung & Analisa', desc: 'Dapatkan total biaya funding dan analisa apakah worth it hold.' },
    ],
    faqs: [
      { q: 'Apa itu funding rate?', a: 'Funding rate adalah biaya berkala yang dibayar antara posisi long dan short dalam perpetual futures. Saat funding positif, long membayar short. Saat negatif, short membayar long. Tujuannya menjaga harga futures mendekati spot.' },
      { q: 'Kapan funding rate bisa menguntungkan?', a: 'Saat funding rate positif tinggi, short position menerima pembayaran funding. Ini bisa dimanfaatkan sebagai sumber passive income dengan strategi cash-and-carry arbitrage.' },
    ],
    references: ['Binance — Funding Rate Mechanics', 'Bybit — Understanding Funding Rate'],
    relatedTools: ['kripto/liquidation-price-analyzer', 'kripto/crypto-risk-manager'],
  },
]

// ─── Helper Functions ─────────────────────────────

export function getToolsByKategori(kategori: KategoriTool): ToolData[] {
  return toolsDatabase.filter(t => t.kategori === kategori)
}

export function getToolBySlug(kategori: KategoriTool, slug: string): ToolData | undefined {
  return toolsDatabase.find(t => t.kategori === kategori && t.slug === slug)
}

export function getAllKategoriTools(): KategoriTool[] {
  return ['trading', 'pajak', 'investasi', 'personal-finance', 'kredit-properti', 'saham', 'kripto']
}

export function getRelatedTools(tool: ToolData): ToolData[] {
  return tool.relatedTools
    .map(ref => {
      const [kat, slug] = ref.split('/')
      return getToolBySlug(kat as KategoriTool, slug)
    })
    .filter((t): t is ToolData => t !== undefined)
    .slice(0, 4)
}

export function getTotalTools(): number {
  return toolsDatabase.length
}

export function getAllTools(): ToolData[] {
  return toolsDatabase
}
